### ISSUE TITLE
Spezifikation: Wiki aufsetzen

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#1]
Für unsere technische Spezifikation brauchen wir eine Wiki Struktur. Anhand dieser Struktur sollte klar sein was wo rein kommt, und wie viel spezifiziert wird.

**Comment by yannisgu** [comment]
@andreasrueedlinger: Bitte das Wiki aufsetzen und dokumentieren, welche Aspekte ein Entwickler dokumentieren/spezifizieren muss beim Entwickeln eines Features

**Comment by yannisgu** [comment]
Danke das Wiki steht soweit?

**Comment by andreasrueedlinger** [comment]
Ja, ist "subject to change", aber die Grundzüge stehen. Kann geschlossen werden.
