### ISSUE TITLE
Evaluation REST API Tooling

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#11]
**Edit**
Sagger und Express sind wohl gesetzt. 
Die Frage ist: Was schreiben wir selber und was lassen wir generieren?
Möglichkeiten: 
- API und Defnitions (so nennnen sich Entytätstypen in Swagger) in der Swagger-Defnition schreiben und Client und Server generieren lassen. 
- API in Swagger-File definieren, Entitäten als TypeScript-Interfaces schreiben, dann aus TypeScript YAML-Defnitionen generieren und aus YAML-API spec referenzieren

**Comment by andreasrueedlinger** [comment]
Falls du mit REST API das Server-side Framework meinst, um das Routing zu handlen, gibt es da wohl für NodeJS nur einen Kandidaten:
http://expressjs.com/

**Comment by andreasrueedlinger** [comment]
Habe nun bei meinen weiteren Abklärungen noch koajs entdeckt, eine Alternative zu expressjs. Ist vom gleichen Team, aber scheint für sie die Zukunft zu sein?!?

**Comment by andreasrueedlinger** [comment]
Habe nochmals Swagger und Co. etwas angeschaut. Was soll uns das API Tooling bringen? Aus meiner Sicht wären folgende Punkte wünschenswert:
- Interaktive API Documentation (Nachschlagewerk für Developer)
- Automatische Validierung der spezifizierten API
- Generierung von Tests für den Serverteil

Etwas weniger wichtig aber nice-to-have:
- Automatische Generierung von Server-Routing Teilen
- Automatische Generierung von Entities
- Automatische Generierung von Client-Code

Bei den letzten Punkten gibt es aber einige Hindernisse:
- So wie es aussieht wird die API mehr oder weniger inkrementell entstehen, Generierung vom Code müsste dann wohl mehr halb-automatisch ablaufen
- Server-Code: es wird nur JS-Code und kein Typescript generiert

Tools/Formate:
- OpenAPI/Swagger vs. API Blueprint
- Swagger Tools vs. Apiary (limited free version)

**Comment by yannisgu** [comment]
@andreasrueedlinger Viele Swagger CodeGen tools arbeiten mit Templates, da könnte man sicher relativ einfach die Code-Generierung der Entitäten bauen.

**Comment by yannisgu** [comment]
**Entscheid 8. August:**
Wir verwenden https://github.com/lukeautry/tsoa zur Generierung der Sagger Spec anhand von TypeScript decorators und kommentaren
