### ISSUE TITLE
Evaluation UI Framework

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#13]

**Comment by yannisgu** [comment]
**Entscheid 8. August:**
https://material.angularjs.org/HEAD/getting-started

**Comment by andreasrueedlinger** [comment]
Hier noch der Link, wie man ev. nur die genützen Zeile von Angular Material einbinden könnte:
https://richardtier.com/2015/06/28/angular-material-design-custom-build-include-only-the-parts-you-need/
Ich weiss aber nicht, ob es bei Angular2 ähnlich läuft.
