### ISSUE TITLE
Refactoring Trainingsarten/Tageswerte-Config

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#15]
Wir hatten davon gesprochen die Trainingsarten/Tageswerte-Config aus der DB zu lösen und in einem JSON-File zu verwalten. Unter Trainingsarten/Tageswerte-Config verstehe ich:
- Definition aller Trainingsarten
- Definition aller Intensitätsbereiche
- Definition aller Einheitenteile
- Definition aller Einheitswerte
- Definitionen aller Tageswert-Felder
- und natürlich der Relationen dazwischen... 

Es gäbe wahrscheinlich 1 Config / Verband, mit seiner ganzen Config. Weiterhin in der DB wären Konfigurationen auf Ebene Gruppe/Team/Verband. 
Damit die Zuordnung weiterhin funktioniert, müssen die "alten" IDs aus der DB ins JSON-File migriert werden. Wir werden also ein Script brauchen, welches das JSON initial aus der DB erstellt. Das JSON legen wir dann im Server-Projekt ab. Ich denke, der Server sollte dann ein API-Endpunkt haben mit der Config. Dieser gibt die Daten aus dem JSON (Verbands-Config) und die Daten aus der DB (Athlet, Team, Gruppe)

@andreasrueedlinger, für dich OK, wenn wir das so umsetzen?

**Comment by andreasrueedlinger** [comment]
Ja wäre für mich ok. Ich würde aber die DB-Struktur und die Daten dort noch behalten (für den Fall, dass wir irgendwie in diese Richtung zurückwollen)

**Comment by andreasrueedlinger** [comment]
Update: grösster Teil des Config-Skripts steht nun. Es fehlen aber noch die Tageswerte und wie in #34 besprochen die Umstellung auf IDs statt keys

**Comment by yannisgu** [comment]
Die restlichen Tasks werden in den Issues #34 und #44 abgearbeitet.
