### ISSUE TITLE
TypeORM Multi-Primary-Column support

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#16]
Wir müssen TypeORM soweit erweitern, dass es Multi-Primary-Column support erhält.

**Comment by andreasrueedlinger** [comment]
Es scheint vorwärts zu gehen bei TypeORM. Composite-Primary-Key-Column wurde implementiert sowie auch neue DB-Drivers (SQLite, Postgres, MariaDB). Ich teste es mal mit unserer DB!

**Comment by andreasrueedlinger** [comment]
Erfolgreicher Test mit Composite Key, sollte dies Woche noch released werden.
