### ISSUE TITLE
Doku T-Pak 3 DB

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#17]
Wie an der SOW-Sitzung besprochen, wird @schaada die T-Pak 3 DB dokumentieren. 

@schaada, mein Vorschlag wäre, dass du mit der Verbands-Trainingsarten-Konfiguration anfängst, die ist mir nämlich am schleierhaftesten. Sobald du etwas hast, wäre es gut, wenn du es mit uns teilst, dann können wir "technischen T-Pak Neulinge" Feedback zu Form und Umfang geben. 
Passt das Vorgehen für dich so?

**Comment by schaada** [comment]
@yannisgu @andreasrueedlinger Ich habe hier (https://github.com/t-pak/code/wiki/Konfiguration-Einstellungen) mal angefangen mit dokumentieren. Würde das für euch so passen bezüglich Form und Umfang?

**Comment by yannisgu** [comment]
Grundsätzlich sehr gut, evtl. Grafik um die Relationen besser verstehen zu
können?

---

Yannis Güdel, Schulweg 28, 1791 Courtaman, Switzerland
Tel: +41 78 795 67 00, Mail: me@yannisguedel.ch

2016-08-18 21:45 GMT+02:00 schaada notifications@github.com:

**Comment by schaada** [comment]
@yannisgu @andreasrueedlinger Entschuldigung, es hat ziemlich lange gedauert. Nun ist aber die Datenbank-Dokumentation zu «Einstellungen/Konfiguration Trainingsarten» (https://github.com/t-pak/code/wiki/Konfiguration-Einstellungen-Trainingsarten) fertig. Es ist nicht nur eine Datenbank-Dokumentation, sondern ich habe da mit den Erklärungen noch etwas tiefer gegangen, deshalb ist es recht umfangreich geworden. Passt das für euch so? Oder fehlt noch etwas? Oder ist es zu ausführlich?

Auf der Startseite (https://github.com/t-pak/code/wiki/Dokumentation-Datenmodell) gibt es zudem eine Liste aller Tabellen mit dem Link, wo sie beschrieben ist.

Welchen Bereich soll ich als nächstes dokumentieren?

**Comment by andreasrueedlinger** [comment]
@schaada Das sieht super aus. Zu ausführlich kann es nicht sein, sonst ist man in einigen Jahren wieder "auf verlorenem Posten" :-) Nächste Tabellen: am besten wäre Personen, Gruppen, Teams und Relationen/Funktionen untereinander (alles was für Zugriffsberechtigungen von Belange ist)

**Comment by andreasrueedlinger** [comment]
@schaada wie sieht es aus bei diesem Vorhaben? Kommst du irgendwann wieder einmal dazu?

**Comment by schaada** [comment]
@andreasrueedlinger Ich hoffe sehr, dass ich da wieder einmal dazu komme. Ich habe es nicht vergessen.

**Comment by schaada** [comment]
@yannisgu @andreasrueedlinger Die Seite Model Organization (https://github.com/t-pak/code/wiki/Model-Organization) habe ich reviewed und ergänzt. Was wäre der nächste Bereich für die Dokumentation? Ich kann nicht garantieren, dass ich das gleich machen kann, aber vielleicht habe ich ja irgendwann Zeit. Die nächste Zeit ist für mich etwas unsicher zu planen, da ich spätestens in zwei Monaten Mutter sein werde.
