### ISSUE TITLE
Abklärungen Hosting

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#18]
@svenmoosb, hier noch ein Issue für dein Task bezüglich Abklärungen mit dem aktuellen Hoster

**Comment by andreasrueedlinger** [comment]
Fazit der Abklärungen: exigo unterstützt NodeJS Hosting momentan und in naher Zukunft nicht. Wir müssen für deploy also neue Hosting-Alternative suchen.
Nach etwas Diskussion in engerer Auswahl:
- [Bluewin developer](https://developer.swisscom.com/pricing)
- [Flow engine](https://flow.ch/appengine/)

Bis es aber aktuell wird kann noch einiges auf dem Markt ändern.
Deshalb: Entscheid swiss-orienteering abwarten und vor dem go-life wieder nach vorne nehmen

**Comment by andreasrueedlinger** [comment]
Entscheid 23.1.17: wir setzen auf [uberspace](uberspace.de). Siehe [Wiki](https://github.com/t-pak/code/wiki/Infrastructure-Documentation).
@yannisgu kann dieser Issue damit geschlossen werden?

**Comment by yannisgu** [comment]
Jep, Ticket zur Konfiguration der Testumgebung: https://github.com/t-pak/issues/issues/38
Update folgt...
