### ISSUE TITLE
Grobarchitektur Client

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#2]
Wir brauchen für den Client eine grobe Architektur. Diese sollte insbesondere folgende Fragen beantworten:
- Nach welchem Prinzip werden Module unterteilt?
- Gibt es etwas wie ein Schichtenmodell oder nicht? (Trennung View/Logik/Datenzugriff) Mein Vorschlag ist View und Datenzugriff zu trennen. Business-Logik und View-logik zu trennen macht aber wohl hier keinen Sinn
- Was ist ein Ordner, was eine Datei. Also eine Datei pro Modul oder ein Ordner pro Modul?

**Comment by yannisgu** [comment]
@andreasrueedlinger wir brauchen insbesondere eine Source-Code Struktur.
Mein Vorschlag für den Client

```
src
|- js
    |- framework
       |- dataService.ts
    |- diary
       |- components
           |- editWorkout
                |- editWorkout.component.ts
                |- editWorkout.html.ts
       |- services
           |- workoutService.ts
           |- commentsService.ts
    |- feature2...
|- css
    |- xx.scss
```

`components` = Views
`services` = Daten-Zugriff

**Comment by andreasrueedlinger** [comment]
Eine Bemerkung zu Aufteilung View-Logik/Business-Logik/Daten-Zugriff: Angular empfiehlt jegliche Logik, die nicht zur "Formatierung" der View dient, in [services auszulagern](https://angular.io/docs/ts/latest/guide/style-guide.html#!#05-15). Ich würde diesen Style Guide folgen und wirklich nur das allernötigste in die View-Komponenten packen und alles andere in Service auszulagern. Das heisst:
`components` = Views
`services` = Business-Logik und Daten-Zugriff, aber in separaten Services.

**Comment by andreasrueedlinger** [comment]
## Vorschlag Clientarchitektur

### Module

Module sind entweder **Komponentenmodule** oder **Servicemodule**, getrennte Module auch wenn das gleiche Feature. Im Arbeitsprozess sollten dann jeweils aber in einem Päckli die Module eines Features zusammengefasst werden.
Beispiel: Päckli "Authentifizierung"
- Servicemodul "Authentifizierungsservice"
- Komponentenmodul "Login" mit allen Login-relevanten Panel-Komponenten (zb auch "logged in as ..." Komponente)

### Komponenten
- Sind primär für die Visualisierung der Daten zuständig
- Daten kommen schon möglichst für die Visualisierung "optimiert"/zugeschnitten vom Service
- einfache Berechnungen und natürlich Formatierung gehört in Komponente

### Services
- Aufbereitung der Daten für die Visualisierung
  - oft Datenzugriff über REST-Service (dieser liefert Daten nicht in View-optimierter Form sondern in performance-optimierter Form und in einem für möglichst viele Clients/Views brauchbaren Modell)
  - ev. aggregieren mit anderen Daten, gewisse Referenzen auflösen
  - Lieferung der Daten für View zugeschnitten (**Optimalfall**: Model in View = Model vom Server, einzig gewisse Referenzauflösungen und Business-Logik-Enhancement)
- Datenvalidierung

### Source-Code Struktur

```
src
|- js
   |- framework
      |- dataService.ts
   |- services
      |- authService.ts
      |- userService.ts
      |- messageService.ts
      |- diary
         |- activityService.ts
         |- diaryViewService.ts
         |- noteService.ts
         |- trackService.ts
   |- components
      |- editWorkout
         |- editWorkout.component.ts
         |- editWorkout.html.ts
      |- login
           |- login.component.ts
           |- login.html.ts
           |- currentUser.component.ts
           |- currentUser.html.ts
      |- editNote
         |- editNote.component.ts
         |- editNote.html.ts
|- css
    |- xx.scss
```

Ich bin dafür dass wir grob in services und components aufteilen, da wir dann auch eine andere Aufteilung für services und components brauchen können, bin aber offen für Argumente dagegen!
Sonst dachte ich, dass wir die Sevices grundsätzlich in einer flachen Struktur halten, ausser die Fileanzahl pro Ordner wird zu hoch (>10 oder so), sodass wir dann für gewisse Services eine Feature-Gruppierung machen.

@yannisgu was meinst du dazu?

**Comment by yannisgu** [comment]
@andreasrueedlinger passt für mich :)

**Comment by andreasrueedlinger** [comment]
Fixiert im [Wiki](https://github.com/t-pak/code/wiki/Architecture-Client)
