### ISSUE TITLE
Build-Scripts für Server

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#20]

**Comment by andreasrueedlinger** [comment]
Build-Scripts (und vieles mehr) Vorschlag als [PR](https://github.com/t-pak/code/pull/6). Es fehlt wohl noch:
- Kopieren package.json
- installieren der node_modules die in production nötig sind
- zippen??

**Comment by yannisgu** [comment]
"production-build" machen wir zu einem späteren Zeitpunkt. Meiner Meinung nach auch davon abhängig, wohin wir deployen:  #27

**Comment by andreasrueedlinger** [comment]
Ok, dann schliessen wir auch  hier
