### ISSUE TITLE
T-Pak Vokabular English finalisieren

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#21]
Ciao @andreasrueedlinger 

Hier noch ein Issue damit wir das technische Vokabular besprechen können.
Anhand der Wiki-Seite nehme ich an, dass Session der Favorit für "Einheit" ist?

| Deutsch | En |
| --- | --- |
| Trainingseinheit | Session |
| Einheitenteil | SessionPart |
| Trainingsart | SessionType |
| Trainingsartklasse | SessionClassificationValue |
| Trainingsartklassierung | SessionClassification |
| Einheitenwert | SessionAttribute oder SessionValue |
| Einheitenwert Auswahl | SessionAttributeChoices |
| Dauer | duration |
| Intensität | intensity |

@andreasrueedlinger was meinst du dazu? Darfst gerne bessere Wörter auswählen, ich bin nicht so Englisch-Afin. Wichtig erscheint mir aber, dass wir möglichst rasch zu einem Entschluss kommen. 

Referenz: https://github.com/t-pak/code/wiki/List-Of-Technichal-T-Pak-Vocabulary

**Comment by andreasrueedlinger** [comment]
Bin jetzt endlich mit meiner englischen Mitbewohnerin zusammengesessen.
Ich denke wir sollten "Activity" für Einheit nehmen. Das ergibt dann:

| Deutsch | En |
| --- | --- |
| Trainingseinheit | Activity |
| Einheitenteil | SubActivity |
| Trainingsart | ActivityType |
| Trainingsartklasse | ActivityDetailOption |
| Trainingsartklassierung | ActivityDetail |
| Einheitenwert | ActivityParameter oder Parameter |
| Einheitenwert Auswahl | ActivityParameterOption oder ParameterOption |
| Dauer | duration |
| Intensität | intensity |

Restliche Wörter siehe im [Wiki](https://github.com/t-pak/code/wiki/List-Of-Technichal-T-Pak-Vocabulary)

**Comment by yannisgu** [comment]
niiice 👍 
Ich wäre eher für ActivityParameter und ActivityParameterOption

**Comment by andreasrueedlinger** [comment]
Ich habe die Liste noch etwas ergänzt und Entscheide getroffen. Ich denke der Grundstock ist dort, falls dann beim loslegen etwas fehlt: Meldung an mich oder selber ergänzen im Wiki
