### ISSUE TITLE
color und icon properties hinzufügen

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#22]
Trainingsarten sollten um ein color und ein icon property erweitert werden:
In den Worten von @andreasrueedlinger  Zusätzlich würde ich gerne im Tree die Referenz auf den Parent haben und dann noch folgende zusätzliche Properties:
- `color`
- `icon` Für die Visualisierung der Activities und SubActivities wird dann die erste definierte Farbe/das erste definierte Icon im Weg nach oben im Tree verwendet. Beispiel: OL hat Farbe grün und ein schönes OL-Icon, alle children verwenden diese beiden Dinge ebenfalls, ausser zB. der OL-Wettkampf der die Farbe dunkelgrün definiert hat.

**Comment by andreasrueedlinger** [comment]
Das Ticket ist wohl etwas früh schon hier, sollte vor allem in den Workshop einfliessen

**Comment by andreasrueedlinger** [comment]
Habe mal vorgespurt bei der config generation und in config model.
Als Test habe ich Testicons von DOSB (https://www.dosb.de/de/service/download-center/medien/sport-piktogramme/) genommen (nur für dev!!) und für 3 Typen Farben und Icons definiert.
PR: https://github.com/t-pak/code/pull/46

**Comment by andreasrueedlinger** [comment]
Wie wir das dann graphisch genau umsetzen, können wir später noch genauer anschauen.
Screenshot vom Test:
<img width="336" alt="grafik" src="https://cloud.githubusercontent.com/assets/9654191/24661439/abc415bc-1952-11e7-9a31-9ea525540e36.png">

**Comment by andreasrueedlinger** [comment]
@jeggi87 Kannst du einmal den momentanen Trainingsarten-Baum überarbeiten und die Farben definieren? Ev. müsstest du da auch noch Feedback von rundherum einholen!
Was aus meiner Sicht am dringensten ist:
* Kategorie "Ergänzende Ausdauer" um Velo, WetWest, etc. zusammenzufassen (auch für Statistiken dann)
* ev. Umbenennung Kraft- und Kräftigungstraining??
* Laufschule ist meiner Meinung nach in der falschen Kategorie. Ich finde persönlich, dass dies kein Lauftraining ist sondern unter die Kategorie "Koordination" fällt bei "Kraft"
* Bei den Krafttrainingsvarianten ist es etwas intransparent welche Einheitenteile wieso wo verfügbar sind. Z.B. vermisse ich "Stabilität" unter "Kombitraining"

**Comment by jeggi87** [comment]
hier ist die Seite mit den Definitionen und den Farben: [UX-Trainingsarten](https://github.com/t-pak/code/wiki/UX-Trainingsarten)
ist noch nicht alles so fix, aber ist mal ein erster Stand.

**Comment by andreasrueedlinger** [comment]
Cool, hier noch einige Bemerkungen:
* die Grundeinteilung "sportartspezifisch"/"ergänzend"/etc ist fix konfiguriert und finde ich so sinnvoll
* ich würde deshalb deine Hauptkategorien als Unterkategorien in diesen vorhandenen unterbringen (nur wo dies nicht schon kongruent ist wie zb bei Mental/Regeneration:
  * OL + Laufen in sportartspezifisch
  * Kraft + ergänzende Ausdauer in "sportartergänzend"
* Ski- und Bike-OL sind ja schon sportartspezifisch für jene welche dies als Hauptsportart machen (und dies ist ja auch in unserem Verband) -> deshalb würde ich noch eine Kategorie Ski-OL und eine Bike-OL in sportartspezifisch machen
* WetWest/Aquajogging: würde ich nur eine Bezeichnung verwenden, Aquajogging ist wohl der bessere
* Atemtraining ≠ Atmungstechnik!! Atemtraining ist wirklich ein Muskeltraining um die Lungenmuskulatur zu trainieren, zB. mit Spyrotiger oä., Atmungstechnik ist mehr "ruhen und auf Atemtechnik achten"
* Massage: finde ich super einen eigenen Typ!! Vermisse ich schon lange

Zu den Farben: du würde ich etwas anpassen, damit wir nicht ein kunterbuntes T-Pak erhalten. Da wir ja Material2/Material Design verwenden und unsere Farbpalette auf den dort definierten Farben basiert, macht es Sinn eine der Hauptfarben von Material zu verwenden:
https://material.io/guidelines/style/color.html

* OL: #43a047 statt #009900
* Laufen: #2962ff statt #0065FF
* Ergänzende Ausdauer: #f44336 statt #FF0000
* Kraft:  #ffeb3b statt #ffff00?? #ffff00 wäre ok, ist aber sehr grell!
* Ausgleich: #bf360c statt #993300
* Regenration: #00e5ff statt #00F5FF
* Mental: #b388ff statt #CC99FF
* TTB-Zusammenfassung: schwarz oder einfach nichts

**Comment by jeggi87** [comment]
super, merci. habe alles umgesetzt.

- Unterteilung kapierte / beachtete ich bis jetzt nicht richtig. habe es nun so umgesetzt wie von dir vorgeschlagen
- Aquajogging: dies ist neu der Begriff
- Atemtraining ≠ Atmungstechnik: stimmt, das eine ist physisches Training, das andere mentales. ich gehe noch etwas den sauberen Begriffen nach
- Massage: machen wir so

Farbe: finde deine Vorschläge gut und habe es mal so korrigiert. Einzig etwas unsicher bin ich bei Ausgleich ob dies nicht zu stark an ergänzende Ausdauer ist. Ich nehme an, dies gibt sehr viel Aufwand, wenn dies dann doch geändert werden muss... Tendiere deshalb eher in Richtung von einem klaren Braun: z.B. #795548

**Comment by andreasrueedlinger** [comment]
@jeggi87 Unterform "Stabilisation": verwende ich momentan sehr häufig und rege mich immer auf, dass sie nicht in "Kombitraining" vorhanden ist. Stabilisation ist Stabitraining, z.B. tiefe Bauchmuskeln trainieren, Einbeistandübungen, Balanceübungen und solches Zeugs. Oder wo würdest du dies unterbringen?

**Comment by andreasrueedlinger** [comment]
@jeggi87 Ich habe ein neuer Issue erstellt: #51, am besten dort weiterdiskutieren

**Comment by andreasrueedlinger** [comment]
[PR](https://github.com/t-pak/code/pull/46) merged
