### ISSUE TITLE
Authentication enhancements

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#26]
Im Moment können wir pro User nur ein Token haben. Das heisst wenn sich ein User auf einem neuen Device einloggt, wird er auf dem anderen Device ausgeloggt. Wir sollten Tokens in einer neuen Tabelle speichern, damit ein User mehrer gültige Tokens haben kann.

**Comment by andreasrueedlinger** [comment]
Ich schlage noch ein Enhancements mehr vor beim Login-Mechanismus:
"angemeldet bleiben" Häkchen beim Login

Implementations-Vorschlag:
* wenn Häkchen angewählt wird token in Browser persistiert (z.B. in localstorage, am besten mit einer polyfill-library mit fallback auf cookie oä.)
* wenn Seite geladen wird wird token von dort gelesen, geprüft und gesetzt
* nice-to-have (siehe github): bei change token in anderem tab wird bei onfocus das aktuelle token mit gespeichertem verglichen und Meldung zu reload angezeigt

**Comment by yannisgu** [comment]
Vorschlag bezüglich priorität:
- Mutli-Token bauen wir irgendwann im Herbst (also nach den wichtigsten Features)
- "angemeldet bleiben" machen wir noch im "T-Pak 5 Base"
- Auf nice-to-have verzichten. Aus meiner Sicht für T-Pak nicht wirtschaftlich. 

Was meinst du @andreasrueedlinger?

**Comment by andreasrueedlinger** [comment]
@yannisgu Ok, bin einverstanden mit dem nice-to-have. Das multi-token habe ich aber schon praktisch fertig implmentiert. Also wirds wohl in den nächsten Milestone kommen. Es gibt eben einen kleinen Umbau beim authenticationService und da ist es wohl besser jetzt gerade alles aufs Mal machen, wenn ich schon voll im Code drin bin. Ok?

**Comment by yannisgu** [comment]
Wenn du sowieso drin bist, unbedingt!

**Comment by andreasrueedlinger** [comment]
PR: https://github.com/t-pak/code/pull/41

**Comment by andreasrueedlinger** [comment]
Hat sich noch ein Bug eingeschlichen, neuer PR: https://github.com/t-pak/code/pull/42
