### ISSUE TITLE
Client Routing

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#28]
Wir brauchen eine initiale Konfiguration fürs Routing auf dem Client.

**Comment by yannisgu** [comment]
FYI: @andreasrueedlinger, ich mache das gerade

**Comment by yannisgu** [comment]
@andreasrueedlinger: PR ist erstellt. Spezifikation/Dokumentation habe ich noch nichts gemacht. Ich bin auch etwas unsicher was  ich genau Dokumentieren soll. Wie eine Route hinzufügen?

**Comment by andreasrueedlinger** [comment]
@yannisgu und Spezifikation: da denke ich es ist es wichtiger die wirklichen Module zu spezfizieren:
- Welche Komponenten, Directives und Services sollen dazu gehören
- Was machen diese genau: Methoden der Services, Teile der Komponenten
- Dies sollte dann zu einem Test-File führen *.spec.ts der diese Dinge testet
  Für den Server ähnlich:
- Welche Routes bietet diese Ressource an, was sind die möglichen Parameter, was die Response
- Spezifikation der Interfaces
- Welche Services braucht es dazu, was machen diese Services genau. Methodenbeschreibung
- Auch hier Testfiles daraus

Aber für das core-Modul Routing würde ich das jetzt auch nicht machen. Aber: am Ende sollte eine Anleitung entstehen wie ein neues Client-Modul geschrieben wird. Dort sollte dann auch enthalten sein, wie eine Route hinzugefügt werden kann.

**Comment by andreasrueedlinger** [comment]
Gemerget
