### ISSUE TITLE
Material in Build integrieren

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#29]
Wir müssen Material 2 irgendwie in unserem Build integrieren.

**Comment by andreasrueedlinger** [comment]
Ist drin oder? Für die Features, die bei material noch fehlen, können wir ev. [primeng](http://www.primefaces.org/primeng) benutzen?

**Comment by andreasrueedlinger** [comment]
Oder materialize-css wäre wahrscheinlich sauberer. Habe es mal integriert in meinem PR [hier](https://github.com/t-pak/code/pull/23)

**Comment by andreasrueedlinger** [comment]
Materialize-css ist wieder draussen. Wir setzen voll auf material 2.
