### ISSUE TITLE
Grobarchitektur Server

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#3]
Wir brauchen für den Server eine grobe Architektur. Diese sollte insbesondere folgende Fragen beantworten:
- Nach welchem Prinzip werden Module unterteilt?
- Gibt es etwas wie ein Schichtenmodell oder nicht? (Trennung View/Logik/Datenzugriff) 
- Was ist ein Ordner, was eine Datei. Also eine Datei pro Modul oder ein Ordner pro Modul?

**Comment by yannisgu** [comment]
@andreasrueedlinger auch für den Server brauchen wir eine Source-Code Struktur

**Comment by andreasrueedlinger** [comment]
Wiki updated
