### ISSUE TITLE
Refactoring Team-Name

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#32]
Aktuell wäre es mit dem DB-schema möglich Team-Namen zu übersetzen. Das ist aber im Code aber nicht umgesetzt, und aus meiner Sicht auch nicht notwendig.  Ich plädiere darum dazu `liste_teams`  mit dem der Spalte `name` auszustatten (und alle Werte aus dem Wörterbuch dorthin zu kopieren). Somit muss für den Parallel-Betrieb der Name in beiden Tabellen gepflegt werden, falls ein Team Namen ändern will. Da dieser Use-Case nur alle paar Jahre vorkommt finde ich das OK.

Was meinst du @andreasrueedlinger

**Comment by andreasrueedlinger** [comment]
@yannisgu gebe auch da die Entscheidungsverantwortung lieber ab :-) Entscheid Verband abwarten. Grundsätzlich wäre es ja schon schöner wenn das "Juniorenkader" bei den französisch-sprachigen Athleten entsprechend anders heisst, nicht?

**Comment by yannisgu** [comment]
Hmm, nein, das ist jetzt wirklich nicht wichtig.

**Comment by andreasrueedlinger** [comment]
Neuer Vorschlag bezüglich mehrsprachigen Namen: https://github.com/t-pak/code/wiki/Translation#dynamic-labels
Verbände/Teams/Gruppen können wählen ob ein- oder mehrsprachig

**Comment by andreasrueedlinger** [comment]
wurde in https://github.com/t-pak/code/pull/51 umgesetzt (Property name). Falls später entschieden wird, dass Mehrsprachigkeit doch unterstützt wird, kann das `DynamicLabel` verwendet werden, das auch bei den custom user data verwendet wird.
