### ISSUE TITLE
Tooling translation / Ablösung Wörterbuch

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#33]
Wir müssen definieren wie wir in Zukunft mit Übersetzung umgehen wollen, und ein Tooling dafür schaffen.

**Comment by yannisgu** [comment]
@andreasrueedlinger ich habe mal einen Entwurf gemacht: https://github.com/t-pak/code/wiki/Translation

Ich habe mir das Tooling von Angular 2 angeschaut und gemerkt, dass es irgendwie nicht unseren Bedürfnissen entspricht. Es kann nämlich mehr oder weniger nur die Werte zu einem XLIFF exportieren und, dann XLIFF wieder "hineinkompillieren".  Für das Management der Übersetzung stellt aber Angular nichts zur verfügung. Und ich habe kein Tool gefunden, welches Gratis ist und wirklich überzeugend ist. Ich schlage darum vor, dass wir unser eigenes kleines Tooling aufbauen und die Übersetzter im Excel arbeiten (ähnlich wie bis anhin). Da für das eigene Tooling JSON viel einfacher ist, schlage ich vor auf https://github.com/ocombe/ng2-translate zu setzen. Mehr Details in der Wiki-Seite.

Was meinst du? Hast du einen anderen Vorschlag?

**Comment by andreasrueedlinger** [comment]
@yannisgu Ich habe heute zufälligerweise auch i18n von angular2 angeschaut und bin zum gleichen Schluss gekommen. Vor allem die dynamischen Übersetzungen (zb. der Name einer Trainingsart) aber auch Attribute von Html-Tags (title zb) werden irgendwie nicht wirklich unterstützt.
Das vorgeschlagene Tool gefällt mir, habe mit dem Vorgänger bei angularV1 gearbeitet und gute Erfahrungen gemacht.
Zum Tooling: finde ich das meiste sehr gut, ausser der Import des bisherigen Wörterbuchs würde ich etwas dynamischer/inkrementell gestalten.
Wir wollen ja jetzt nicht mehr numerische Ids im lang.json-File, sondern sprechende Labels, oder?
Ich würde ein kleines Tool schreiben, das neue Labels kreieren kann und dann im mysql-woerterbuch nach entsprechenden, vorhandenen Einträgen suchen kann.

**Comment by yannisgu** [comment]
Hmm, also mein Vorschlag hätte auch keine IDs im `de.json`. 
Nur im `translationMapping.json`. Welches "nur" für Übergangsphase da ist. Das brauchen wird, damit wir die "alten" Einträge zu einem späteren Zeitpunkt exportieren können, weil ja nun das "alte" T-Pak auf Tschechisch übersetzt wird. 

Aber kannst du dein Vorschlag noch etwas detaillierter beschreiben? Was würde das Tool genau machen. Also angenommen ich brauche das Wort "Dauer". Ich rufe `node xxxx.js Dauer` auf. Was passiert dann?

**Comment by andreasrueedlinger** [comment]
Ok, ich habe wahrscheinlich vorhin deine Idee nicht ganz verstanden. Also wenn ich es jetzt richtig sehe übersetzt dein `migrateDictionary.js` alle "dynamischen" Labels (alle welche irgendwo in der DB referenziert sind)?
Ich habe mehr an die fixen Labels gedacht wie "du hast keine neuen Mitteilungen", "Home", "Zugriff", "Kommentar erfassen" etc. Da sollten wir ja auch neue label-Ids im xx.json erstellen, aber falls immer möglich die bisherigen Übersetzungen verwenden.
Ich dachte da an ein Skript, das man starten kann `node xxx.js` und dann als CL-Applikation läuft:
- Suchfunktion, um im alten Wörterbuch Einträge suchen, die Query-Text enthalten
- erstellen von neuen Labels ohne Hilfe
- erstellen von neuen Lables mithilfe der Suchfunktion und gefundenen Treffern (Auswahl Treffer, Zuordnung zu neuem Label, oder einfach nur Einblendung eines Treffers als Hilfe zur Erstellung eines neuen Lables, zb wenn nur ein Teil davon verwendet wird)

**Comment by yannisgu** [comment]
Ja das migrateDictionary würde alle alten Mappings aus der DB in ein neues File in unserem gewünschten Format migrieren. 
Die Idee ist, dass wir schon jetzt Labels in Angular brauchen können, wir aber die Migration von DB => Config-File immer wieder machen können. So stellen wir sicher, dass Tschechisch nicht noch mal fürs neue T-Pak übersetzt werden muss.

**Comment by andreasrueedlinger** [comment]
@yannisgu nachdem ich die Tabellen der Datenbank durchgegangen bin, finde ich dass wir dynamische Labels unterstützen müssen. Ich habe aber eine Idee, wie wir die language files trotzdem mit dem Release rausgeben können und dennoch dynamische Änderungen möglich sind.
Siehe https://github.com/t-pak/code/wiki/Translation#static-and-dynamic-labels

**Comment by yannisgu** [comment]
@andreasrueedlinger sieht grundsätzlich gut aus. 
Einzig: Ich weiss noch nicht ob ich mit dem letzten Abschnitt einverstanden bin.
> Release: when releasing a new version, the dynamic dicionary is exported to the json files for the next version and the table is emptied.

Warum? Können wir uns nicht darauf einigen: static = file, dynamic = db.
Ich würde den Release-Prozess gerne so einfach wie möglich und so automatisch wie möglich machen. Da ist jeder Schritt, der verhindert werden kann "zu viel".

**Comment by andreasrueedlinger** [comment]
@yannisgu ok, ja das können wir. Ich dachte einfach so gäbe es etwas weniger Serveraufrufe. Dafür wird das json halt grösser. Release-Prozess einfach halten finde ich aber gut.

**Comment by andreasrueedlinger** [comment]
Erste Version des Skript Tools: https://github.com/t-pak/code/pull/34

**Comment by andreasrueedlinger** [comment]
PR https://github.com/t-pak/code/pull/34 merged
