### ISSUE TITLE
Tpak 4 "erweitern" button führt zu reload

### ISSUE THREAD

**Issue by jeggi87** [t-pak/issues#35]
Klickt man in einem Formular auf den "Erweitern" Button dann gehen alle im Formular eingetragenen Werte verloren, da das Formular neu geladen wird. Kann dies verhindert werden?

**Comment by yannisgu** [comment]
Hey @jeggi87 

Ich nehme an du sprichst von der Luppe in der Ansicht um eine Einheit anzulegen/editieren? 
Theoretisch könnte die Einheit gespeichert werden bevor die Ansicht geändert wird. 
Der Aufwand dafür würde wohl 2-3PT sein. Ich denke nicht, dass es das wert ist? 
Wir werden aber schauen, dass im T-Pak 5 das besser gelöst ist ;)

**Comment by jeggi87** [comment]
Hoi @yannisgu 

ja es geht um die Lupe.
für diesen Aufwand lohnt es sich nicht. 
Idee: wäre es möglich eine Bestätigung ein zubauen? Also dass eine Frage kommt, "Willst du wirklich die "Lupe" ausführen?" Button Ja / Abbbrechen. Dann könnte man nämlich dort auch noch hinschreiben, "Achtung, die Daten im Formular gehen verloren. Umgehen via Abbrechen, Speichern und dann Einheit editieren."
Falls haltest du davon?

**Comment by andreasrueedlinger** [comment]
@jeggi87 eigentlich haben wir ja entschieden, dass wir kein Bugfixing im T-Pak 3/4 machen, ausser es ist wirklich "produktionsgefährdend". Dein Problem würde ich jetzt aber in der Priorität eher tief einstufen (ist ja schon immer so) und deshalb nicht mehr angehen und die Ressourcen auf Version 5 verwenden.

**Comment by jeggi87** [comment]
@andreasrueedlinger und @yannisgu 
ja ruud hat recht, es ist nicht relevant und vor allem, es ist schon seit beginn an so. lassen wir dies. Dachte anfangs es sei ev. nur eine Einstellung im Formular, die es ermöglichen würde. Konzentrieren wir uns auf die neue Version.

**Comment by andreasrueedlinger** [comment]
Won't fix
