### ISSUE TITLE
Datenbank Migrationen

### ISSUE THREAD

**Issue by andreasrueedlinger** [t-pak/issues#36]
Wir müssen ein einfaches Verfahren haben, um die Datenbank-Struktur anzupassen (lokal Development + Server), damit überall auf den gleichen Datenbank-Schemas gearbeitet wird. Zudem müssen auch die Daten migriert werden bei solchen Updates.

**Comment by andreasrueedlinger** [comment]
Sollte hier kommen: https://github.com/t-pak/code/wiki/HowTo-Migration-Databasemodell

**Comment by andreasrueedlinger** [comment]
Zudem dazugehörende Links:
https://github.com/t-pak/code/wiki/Dokumentation-Datenmodell
https://github.com/t-pak/code/wiki/Datenbankmanagement

**Comment by andreasrueedlinger** [comment]
Entwicklungsdatenbank: Entwickler sollten die Grundstruktur, eine Ausgangsversion vor allen Migrationen, downloaden können. Dies sollten nicht die "Live-Daten" sein (Datenschutz und Grösse, > 1GB).
Idee:
1. Live-DB kopieren
2. alte Daten löschen
3. "intime" Daten anonymisieren
4. zippen und auf Github? laden

*UPDATE*: 
Ich habe ein Skript geschrieben, der dies macht. Es macht folgende "Anonymisierungen":
* Einheiten: Titel, Ort und Wetter durcheinandermischen, Bemerkungen: Zufallstext
* Foreneinträge: Zufallstexte
* Nachrichten: Zufallstexte
* Personen: Zufallsnamen, neuer Nickname, Pasword=Nickname, Zufallsemail, Zufallsadresse, -telefon, -geburtsdatum und Klubs, fotopfad und www durcheinandermischeln
* Tageskommentare: Zufallstext
* Trainerbereichkommentare: Zufallstext
* Ziele: Zufallstexte
* Zielkommentare: Zufallstext
* Events und Minievents: Titel und Beschreibung durcheinandergemischt
* Zusätzliche Gruppen/Team/Verbandsvariablen Personen (SI-Nr, Solv-Nr, ...): durchmischeln
* Eventvariablen bei Anmeldungen: Werte durchmischeln
* Anmeldungen: Bemerkungen: Zufallstext

**Comment by andreasrueedlinger** [comment]
Updated
https://github.com/t-pak/code/wiki/Database-Management
und
https://github.com/t-pak/code/wiki/HowTo-Migration-Databasemodel

@yannisgu  was meinst du dazu?

**Comment by andreasrueedlinger** [comment]
Siehe https://github.com/t-pak/code/pull/39

**Comment by yannisgu** [comment]
Gute Idee 👍  
Ich denke wir laden das ZIP eher auf Uberspace herauf (evtl. mit basic auth geschützt)

**Comment by yannisgu** [comment]
Offene Tasks:
- [ ] ZIP auf Ubserspace passwort geschützt laden
- [ ] Link dokumentieren

Sonst noch was @andreasrueedlinger?

**Comment by andreasrueedlinger** [comment]
@yannisgu siehe Kommentar beim [PR](https://github.com/t-pak/code/pull/43), was meinst du zu den typeorm migrations?

**Comment by andreasrueedlinger** [comment]
ZIP hochgeladen und Link im Wiki, deshalb: closing issue
