### ISSUE TITLE
Coding Guidelines

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#4]
Wir brauchen etwas an Coding Guidelines. Für den Anfang wohl nicht alzu umfangreich, aber es sollte wenigstens geklärt werden, was camelCase und was PascalCase geschrieben wird.

**Comment by andreasrueedlinger** [comment]
Ich schlage vor, dass wir für Client und Server dasselbe tslint.json verwenden und so die "groben" Guidelines per tslint abdecken. Die zusätzlichen Guidelines und die Hauptpunkte werden noch im Wiki erläutert.

**Comment by andreasrueedlinger** [comment]
Guidelines im Wiki festgehalten: https://github.com/t-pak/code/wiki/Guidelines, deshalb schliesse ich diesen Konzeptionsabschnitt. Das heisst nicht, dass es keine Anpassungen mehr geben kann!
