### ISSUE TITLE
T-Pak 4 Fehler auf der Produktion: Undefined index: ordner

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#40]
Folgender Fehler ist auf der Produktion mehrmals aufgetreten:
```
Error	
Undefined index: ordner
Errno	
8
File	/home/web/1498391366288304463452/htdocs/tpak4/logic/jsonManager.php
Line	96
Url	/tpak4/json/datasource.php
Trace	
Array
(
    [0] => Array
        (
            [file] => /home/web/1498391366288304463452/htdocs/tpak4/logic/errorHandler.php
            [line] => 36
            [function] => format_error
            [args] => Array
                (
                    [0] => 8
                    [1] => Undefined index: ordner
                    [2] => /home/web/1498391366288304463452/htdocs/tpak4/logic/jsonManager.php
                    [3] => 96
                    [4] => /tpak4/json/datasource.php
                    [5] => 
                    [6] => 
                    [7] => 
                    [8] => 
                )

        )

    [1] => Array
        (
            [function] => fatal_handler
            [args] => Array
                (
                )

        )

)
```

**Comment by andreasrueedlinger** [comment]
Seit wann ist `undefined index` bei php ein `fatal error`? Dachte das spukt nur eine Warnung raus

**Comment by andreasrueedlinger** [comment]
Sorry, gibt sogar nur ein `Notice` bei `undefined index`. Man beachte `Errno 8` was nur ein Notice ist, siehe http://php.net/manual/de/errorfunc.constants.php:

Wert|Konstante|Beschreibung|Bemerkung
---|---|---|---
1|```E_ERROR (integer) ```|Fatale Laufzeit-Fehler. Dies zeigt Fehler an, die nicht behoben werden können. Beispielsweise Probleme bei der Speicherzuweisung. Die Ausführung des Skripts wird abgebrochen. 	|
2 |```E_WARNING (integer)``` |Warnungen (keine fatalen Fehler) zur Laufzeit des Skripts. Das Skript wird nicht abgebrochen. 	|
4 |```E_PARSE (integer) ```|Parser-Fehler während der Übersetzung. Parser-Fehler können nur vom Parser erzeugt werden. 	|
8 |```E_NOTICE (integer) ```|Benachrichtigungen während der Laufzeit. Sie zeigen an, dass im Skript irgend etwas gefunden wurde, was einen Fehler verursachen könnte. Es ist aber genauso möglich, dass Benachrichtigungen im ordnungsgemäßen Ablauf eines Skripts ausgegeben werden. |
