### ISSUE TITLE
Refactoring Tageswerte

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#44]
Die Konfiguration der Tageswerte muss noch in die Config-Files migriert werden.

**Comment by andreasrueedlinger** [comment]
Done, siehe PR https://github.com/t-pak/code/pull/45
Einige Änderungen zum bisherigen DB-Modell:
- überflüssige Tabelle (mit `var` Spalte) so einfach ausgeblendet im config file
- zusätzlich `type` und `metric` eingefügt um einheitliche Masseinheiten zu haben von jetzt an und die Typen zu validieren

Weitere TODOs:
- [x] `cm` als Masseinheit hinzufügen
- [x] Körpergrösse: Eingabewerte "normalisieren", zu gleicher Einheit konvertieren, Vorschlag `cm`
- [x] Tageswerte werden momentan in hard-coded Spalte in `liste_tage` geschrieben. Behalten wir das so bei und fügen Spalte hinzu bei Änderungen Tageswerte (sollten ja eigentlich nicht mehr so viele sein und nur noch über einen Release über config-File möglich sein) oder dynamischeres Setup mit Relationstabelle? Oder nur eine Spalte Tageswerte, wo ein JSON geschrieben wird?

**Comment by andreasrueedlinger** [comment]
@yannisgu was meinst du zu den offenen Punkten?

**Comment by andreasrueedlinger** [comment]
Ist mittlerweile abgeschlossen
