### ISSUE TITLE
Schätzungen für Feature Modules 1 überprüfen

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#46]
Die Schätzungen für die Features "Trainingserfassung", "Listen-Ansicht" und "Tageswerte" muss überprüft aufgrund der detaillierten Konzeption überprüft werden. 

Sobald die Konzeption des Analyse-Bereichs abgeschlossen ist (#45), muss dieser ebenfalls geschätzt werden.

**Comment by andreasrueedlinger** [comment]
\+ "Einstellungen/Benutzerprofil"

**Comment by andreasrueedlinger** [comment]
Schätzungen überprüft und im Wiki dokumentiert:
https://github.com/t-pak/code/wiki/UX
