### ISSUE TITLE
Client Routing

### ISSUE THREAD

**Issue by andreasrueedlinger** [t-pak/issues#47]
Wir müssen das Routing im Client "nach allen Regeln der Kunst" aufsetzen und für all die kommenden Feature-Module vorspuren.
Ich habe einmal die Routing Architektur etwas versucht zu skizzieren:
https://github.com/t-pak/code/wiki/Client-Routing

@yannisgu was meinst du dazu?

**Comment by andreasrueedlinger** [comment]
Dazugehöriger PR: https://github.com/t-pak/code/pull/40

**Comment by yannisgu** [comment]
Ciao Ruud

Gefällt mir sehr gut das Ganze.
Ich habe eigentlich keine Bemerkungen/Einwände zur Wiki-Seite

**Comment by andreasrueedlinger** [comment]
Merged https://github.com/t-pak/code/pull/40
