### ISSUE TITLE
Wiki und Multi Language 

### ISSUE THREAD

**Issue by jeggi87** [t-pak/issues#49]
Konntet ihr euch das Thema Wiki als Hilfe mal anschauen?
Wenn dies mal aufgesetzt wäre könnte ich gut selbstständig an diesem Arbeiten. Einfach dies mit der Sprache muss geklärt sein.
Gleiches gilt auch fürs T-pak und alle Sprachen: Dies hängt ja teils auch mit der Hilfe zusammen. Auch hier würde ich mich um die verschiedenen Begriffe kümmern (es hat ja auch noch einige Fehler), wenn ich von euch eine Liste bekomme mit allen Begriffen, die zu übersetzten sind.

**Comment by andreasrueedlinger** [comment]
@jeggi87 T-Pak und Sprachen: siehe https://github.com/t-pak/code/wiki/Translation, wir können ein csv-File rausspucken für eine Sprache. Wenn dies übersetzt ist, lesen wir das csv wieder ein

**Comment by jeggi87** [comment]
ok, sieht gut aus.
Thema Wiki: da könnte ich wirklich dran arbeiten, wenn ihr mir dies einrichten könnt. Übersetzung ist wohl dann eher später.

**Comment by andreasrueedlinger** [comment]
ist nun eingerichtet
