### ISSUE TITLE
Überarbeiten Trainingsarten

### ISSUE THREAD

**Issue by andreasrueedlinger** [t-pak/issues#51]
Trainingsarten sollten wieder einmal überarbeitet und hinblicklich neue Funktionalitäten überprüft werden.
Siehe Wiki: https://github.com/t-pak/code/wiki/UX-Trainingsarten

Anpassungen sollten soweit möglich schon in T-Pak 4 umgesetzt werden (als Verbandsadmin) und danach per Skript automatisch übernommen werden.

**Comment by andreasrueedlinger** [comment]
Ich habe erste Änderungen als Verbandsadmin vorgenommen:
* die schon vorhandene Trainingsart "ergänzendes Ausdauertraining" aus "nicht zugeordnet" zu "sportartergänzend" geschoben und die entsprechenden Trainingsarten "darin versorgt".
* Massage als separate Trainingsart definiert unter Regeneration

**Comment by jeggi87** [comment]
super, passt.
zum Thema "Stabilisation" unter Kraft: ich verstehe darunter auch das gleiche wie du Ruud, also die Muskeln die für die Körper Stabilisation zuständig sind. Nur passt es dann für mich nicht zu den anderen Begriffen wie: Maximalkraft, Muskelausdauer und Muskelquerschnitt. Das sind Formen wie du die Muskulatur trainierst. Die Stabilisationsübungen sind (meist) Muskelausdauer Trainings. Du trainierst da die Ausdauer und nicht z.B. die Maximalkraft. Stabilisationsübungen sind ein Teilbereich des Krafttrainings (ohne anzugeben wie du diese trainierst), ähnlich wie "Oberarm-Training" oder "Fussgymnastik". Ich finde dies eben vermischt und werde dies mit Experten anschauen und ausdisktuieren wie es gelöst werden soll.

**Comment by andreasrueedlinger** [comment]
Spezifikation: https://github.com/t-pak/code/wiki/UX-Trainingsarten
Umsetzung wenn möglich schon in T-Pak 4, sonst ins Migrationsskript einbauen

**Comment by andreasrueedlinger** [comment]
Siehe auch #76
