### ISSUE TITLE
Upgrade auf npm 5

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#53]
@andreasrueedlinger @LukasSkywalker habt ihr euch schon mit npm 5 auseinandergesetzt? 
Denke es würde Sinn machen zu "upgraden". Meine primäre Motivation ist package-lock-json, sodass unsere npm-dependencies etwas stabiler werden.  Konkret würde das heissen:
- Requirements im Wiki anpassen
- Node Version lokal updaten
- package-lock.json commiten

Was meint ihr?

**Comment by andreasrueedlinger** [comment]
Habe mir npm 5 jetzt etwas angeschaut und das lockfile macht wirklich Sinn. Ist ja gerade jetzt wieder aufgetreten so ein Fall, der einfach den build verhaut. Bin also für das Update!

**Comment by andreasrueedlinger** [comment]
merged https://github.com/t-pak/code/pull/59
npm 5 scheint aber auch noch etwas buggy, musste jetzt schon 2-3 mal ganzes node_modules Directory und das lock-file löschen und alles neu installieren. Sonst ging plötzlich die angular-cli nicht mehr nach einem branch Wechsel

**Comment by andreasrueedlinger** [comment]
mittlerweile läuft npm 5 schon sehr stabil. 
@yannisgu Müssen wir die genaue Version festlegen oder sollen wir hier schliessen?
