### ISSUE TITLE
Einheitenwert Borg muss bei allen Trainingsarten ausgewählt werden

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#56]
In der Trainingskonfiguration müssen wir den Borg Einheitenwert allen Trainingsarten zuweisen.

**Comment by andreasrueedlinger** [comment]
@jeggi87 @yannisgu Borg soll bei ganz allen Trainingsarten dabei sein oder bei allen "sportlichen" bzw. allen in sportartspezifisch, ergänzend und Ausgleich? Regeneration und Mental macht wenig Sinn oder?

**Comment by andreasrueedlinger** [comment]
Ich habe nun als Verbandsadmin in Tpak4 bei allen Trainingsarten unter sportartspezifisch, sportartergänzend und Ausgleich Borg hinzugefügt. So wie es aussieht müsste man aber einmal alle diese Werte überarbeiten und schauen, was wo sinnvoll ist. Z.B. hat es fast bei allen Arten "Trainingsbelastung" mit Einheit Foster und nun halt auch noch den Borg. Ist etwas doppelt gemoppelt.

**Comment by andreasrueedlinger** [comment]
Config überarbeitet
