### ISSUE TITLE
Umsetzung Listenansicht

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#57]
## API endpoints
- [x] API preferences (Filter-/Anzeigeeinstellungen) (1PT)
- [x] API activities (offen: planned activities, etwas aufräumen) (4h)
- [x] API Vorlagen: -> Trainingserfassung
- [x] API Tageswerte: -> Tageswerte
- [x] API Kommentare: -> Kommentare
- [x] API Gruppen/Teams: -> User Profil
- [x] API "meine" Athleten (4h)

##  Client Services
- [x] Services für alle API endpoints oben (4h)

## UX Komponenten
- [x] Parent Seite TTB (2h)
- [x] Komponente Listenansicht (1PT)
- [x] Komponente Ansichtsfilter (4h)
- [x] Komponente Athletenauswahl in Sidenav (6h)
- [x] Komponente Schnelllinks (Vorlagen, recent) in sidenav? (1PT)
- [x] Komponente Tage mit Buttons (wird nun in Komponente Listenansicht umgesetzt) (4h)
- [x] Komponente Tageswerte (1PT)
- [x] Komponente Kommentare (1PT)
- [x] Komponente Einheiten-Card Short/Detailed (2.5PT)
- [x] Seite Detailsansicht, erste rudimentäre Version (1PT)
- [ ] Statistiken (-> in Analyse geschätzt)

Total: 12 PT
Originale Schätzung: 12PT

**Comment by andreasrueedlinger** [comment]
@yannisgu sorry, habe deinen "Initial-Comment" geändert, da nur die checklists dort auch erkannt werden in der Übersicht :-)

**Comment by andreasrueedlinger** [comment]
Schliesse den Issue und öffne einen neuen für die Integration der Analyse
