### ISSUE TITLE
Bug: Drag and Drop bei "anderem" User

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#69]
Mir ist aufgefallen, dass wenn ich den Edit-Modus für einen betreuten Athleten öffne, wo ich Schreib-Rechte habe, das Drag and Drop nicht richtig funktioniert. 

Wenn ich eine Vorlage oder eine Einheit reinziehe, wird diese auch beim aktuellen User dargestellt und nicht beim User, wo der Edit modus aktiv ist. Gespeichert wird die Einheit jedoch beim korrekt User. 
![](https://i.imgur.com/jSLBtEB.gif)

**Comment by andreasrueedlinger** [comment]
fixed in https://github.com/t-pak/code/pull/139

**Comment by andreasrueedlinger** [comment]
PR merged
