### ISSUE TITLE
Build-Scripts für Client

### ISSUE THREAD

**Issue by yannisgu** [t-pak/issues#9]
Wir brauchen v.a. fürs Frontend automatisierte Build-Scripts. 

Anforderungen Frontend:
- Transformieren von LESS zu CSS
- Kompillieren von TS zu JS
- Kompillieren der HTML-Views zu einem JS-File
- File-Watcher

Anforderungen Backend:
- Transpielierung Typescript (inkl. Einbindung externer References), Output in build-directory
- Lint für Einhaltung Coding-Guidelines

**Comment by andreasrueedlinger** [comment]
Auch fürs Backend braucht es Build-Scripts.
Ich schlage gulp vor, macht einen guten Eindruck auch im Zusammenspiel mit Typescript-Transpilierung.

Anforderungen Backend:
- Transpielierung Typescript (inkl. Einbindung externer References), Output in build-directory
- Lint für Einhaltung Coding-Guidelines

Wie setzen wir das Projekt auf?
- Client und Server sharen package.json und andere Konfigurationen?
- ev. sogar nur ein Build-Script mit unterschiedlichen Tasks?
- 2 (bis 3) separate Folders für Client, Server und shared (Model) mit eigenen Konfigurationen

**Comment by yannisgu** [comment]
@andreasrueedlinger Wie setzen wir das Projekt auf?
Ich würde Client/Server eher trennen: Also je ein package.json, je ein gulpfile.js. Der shared-Folder hat kein Build-System, nur Klassen/Module, welche aus Klassen/Module vom Client/Server Projekte Refenziert werden können. 

Der Grund ist vorallem, dass obwohl beides TypeScript ist, das Paketieren zimliech unterschiedlich ist. Auch finde ich, solte klar sein welche depdendencies zum Client und welche zum Server gehören. 

Ich habe ein bisschen ausprobiert, aber ich bin noch auf keinen grünen Zweig gekommen.

**Comment by andreasrueedlinger** [comment]
Da ich den Client-Build Scripts PR gemerget habe (https://github.com/t-pak/code/pull/2), schliesse ich auch diesen Konzeptionspunkt.
